# Generated by Django 3.0 on 2019-12-22 04:20
import os

from django.contrib.auth.models import User
from django.db import migrations


def generate_superuser(apps, schema_editor):
    django_su_name = os.environ.get('DJANGO_SU_NAME')
    django_su_email = os.environ.get('DJANGO_SU_EMAIL')
    django_su_password = os.environ.get('DJANGO_SU_PASSWORD')

    superuser = User.objects.create_superuser(
        username=django_su_name,
        email=django_su_email,
        password=django_su_password
    )

    superuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
