version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    depends_on:
      - db
      - pgadmin
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=leonime
      - POSTGRES_PASSWORD=nomas123
      - POSTGRES_DB=codeshepherds
  pgadmin:
    build: ./pgadmin
    volumes:
      - ./pgadmin/data/:/var/lib/pgadmin
      - ./pgadmin/data/:/servers.json
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=leonime
      - PGADMIN_DEFAULT_PASSWORD=nomas123
    ports:
      - 5050:5050
    depends_on:
      - db

volumes:
  postgres_data: {}
