version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env.prod.db
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_data:/servers.json
    ports:
      - 6543:6543
    env_file:
      - ./.env.pgadmin
    depends_on:
      - postgres
  django:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn codeshepherds.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./web/.env
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 81:80
    depends_on:
      - django

volumes:
  postgres_data: {}
  pgadmin_data: {}
  static_volume: {}
  media_volume: {}
