version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.configs/postgres/.env
    secrets:
      - postgres_user
      - postgres_password
      - postgres_database
    networks:
      - codeshepherds-backend
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_data:/servers.json
    env_file:
      - ./.configs/pgadmin/.env
    ports:
      - 5050:5050
    depends_on:
      - postgres
    networks:
      - codeshepherds-backend
      - codeshepherds-frontend
  redis:
    image: "redis:5-alpine"
    networks:
      - codeshepherds-backend
  celery:
    build: ./web
    command: celery -A codeshepherds worker -l info
    secrets:
      - django_db_name
      - django_db_password
      - django_db_port
      - django_db_user
      - django_db_host
      - django_db_engine
      - django_su_name
      - django_su_email
      - django_su_password
      - secret_key
      - django_settings_module
      - load_from_environment
      - database
      - sql_host_test
      - sql_port_test
      - dropbox_access_token
      - sentry_dsn
      - redis_url
    environment:
      - CONTAINER=celery
      - STAGE=development
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - DEBUG=1
      - ENV_SECRETS_DEBUG=true
      - LOGLEVEL=debug
    env_file:
      - ./.configs/django/.env
    volumes:
      - ./web/:/usr/src/app/
      - django_staticfiles:/usr/src/app/static/
      - django_mediafiles:/usr/src/app/media/
    depends_on:
      - postgres
      - redis
    networks:
      - codeshepherds-backend
  django:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    secrets:
      - django_db_name
      - django_db_password
      - django_db_port
      - django_db_user
      - django_db_host
      - django_db_engine
      - django_su_name
      - django_su_email
      - django_su_password
      - secret_key
      - django_settings_module
      - load_from_environment
      - database
      - sql_host_test
      - sql_port_test
      - dropbox_access_token
      - sentry_dsn
      - redis_url
    volumes:
      - ./web/:/usr/src/app/
      - django_staticfiles:/usr/src/app/static/
      - django_mediafiles:/usr/src/app/media/
    ports:
      - 8000:8000
    environment:
      - CONTAINER=development
      - STAGE=development
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - DEBUG=1
      - ENV_SECRETS_DEBUG=true
      - LOGLEVEL=debug
    env_file:
      - ./.configs/django/.env
    depends_on:
      - postgres
      - celery
      - pgadmin
    networks:
      - codeshepherds-backend
      - codeshepherds-frontend

secrets:
  database:
    file: ./secrets/database
  django_db_engine:
    file: ./secrets/django_db_engine
  django_db_host:
    file: ./secrets/django_db_host
  django_db_name:
    file: ./secrets/django_db_name
  django_db_password:
    file: ./secrets/django_db_password
  django_db_port:
    file: ./secrets/django_db_port
  django_db_user:
    file: ./secrets/django_db_user
  django_settings_module:
    file: ./secrets/django_settings_module
  django_su_email:
    file: ./secrets/django_su_email
  django_su_name:
    file: ./secrets/django_su_name
  django_su_password:
    file: ./secrets/django_su_password
  dropbox_access_token:
    file: ./secrets/dropbox_access_token
  load_from_environment:
    file: ./secrets/load_from_environment
  postgres_database:
    file: ./secrets/postgres_database
  postgres_password:
    file: ./secrets/postgres_password
  postgres_user:
    file: ./secrets/postgres_user
  redis_url:
    file: ./secrets/redis_url
  secret_key:
    file: ./secrets/secret_key
  sentry_dsn:
    file: ./secrets/sentry_dsn
  sql_host_test:
    file: ./secrets/sql_host_test
  sql_port_test:
    file: ./secrets/sql_port_test

volumes:
  postgres_data: {}
  pgadmin_data: {}
  django_staticfiles: {}
  django_mediafiles: {}

networks:
  codeshepherds-backend:
  codeshepherds-frontend:
