# Generated by Django 2.1.7 on 2019-02-13 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.CharField(max_length=16, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('country_code', models.CharField(max_length=4, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('found', models.BooleanField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SURLAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.ShortURL')),
            ],
        ),
        migrations.AddField(
            model_name='geolocation',
            name='surl_analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.SURLAnalytics'),
        ),
    ]
