# Generated by Django 2.1.5 on 2019-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='country_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='ipv4',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
