# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import party.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=50)),
                ('date_of_party', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=party.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Wish'),
        ),
    ]
