# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='_from',
            new_name='w_from',
        ),
    ]
