# Generated by Django 3.0.8 on 2020-07-09 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import thumbnails.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='The content of the chirp.', null=True)),
                ('image', thumbnails.fields.ImageField(blank=True, help_text='An image.', max_length=1024, null=True, upload_to='chirp/chirp/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time when the chirp was created.')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalChirpLike',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chirp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chirp.Chirp')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical chirp like',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalChirp',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='The content of the chirp.', null=True)),
                ('image', models.CharField(blank=True, help_text='An image.', max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(blank=True, editable=False, help_text='The time when the chirp was created.')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='The parent chirp.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chirp.Chirp')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Who is the owner of the chirp.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical chirp',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ChirpLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chirp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chirp.Chirp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chirp',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='It keeps a record on who likes the chirp.', related_name='chirp_user', through='chirp.ChirpLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chirp',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent chirp.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chirp.Chirp'),
        ),
        migrations.AddField(
            model_name='chirp',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who is the owner of the chirp.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
