# Generated by Django 3.0.7 on 2020-07-02 10:21

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', thumbnails.fields.ImageField(blank=True, help_text='The picture', null=True, upload_to='pictures/profile/%Y/%m/%d/')),
            ],
        ),
    ]
