# Generated by Django 2.1.5 on 2019-02-10 09:58

from django.db import migrations, models

import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=2083, validators=[shortener.validators.validate_url]),
        ),
    ]
